name: mockwebserver_dart
description: A mock web server for testing HTTP clients, with support for path parameters, handler management, and built on top of shelf.
version: 0.1.0
repository: https://github.com/yshrsmz/mockwebserver-dart

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.2
  # path: ^1.8.0

dev_dependencies:
  http: ^1.4.0
  lints: ^6.0.0
  test: ^1.24.0
