name: mockwebserver
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/yshrsmz/mockwebserver-dart

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.2
  # path: ^1.8.0

dev_dependencies:
  http: ^1.4.0
  lints: ^5.0.0
  test: ^1.24.0
